 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/feedbacks", type: :request do

  # Feedback. As you add validations to Feedback, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Feedback.create! valid_attributes
      get feedbacks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      feedback = Feedback.create! valid_attributes
      get feedback_url(feedback)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    xit "renders a successful response" do
      get new_feedback_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      feedback = Feedback.create! valid_attributes
      get edit_feedback_url(feedback)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Feedback" do
        expect {
          post feedbacks_url, params: { feedback: valid_attributes }
        }.to change(Feedback, :count).by(1)
      end

      it "redirects to the created feedback" do
        post feedbacks_url, params: { feedback: valid_attributes }
        expect(response).to redirect_to(feedback_url(Feedback.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Feedback" do
        expect {
          post feedbacks_url, params: { feedback: invalid_attributes }
        }.to change(Feedback, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post feedbacks_url, params: { feedback: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested feedback" do
        feedback = Feedback.create! valid_attributes
        patch feedback_url(feedback), params: { feedback: new_attributes }
        feedback.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the feedback" do
        feedback = Feedback.create! valid_attributes
        patch feedback_url(feedback), params: { feedback: new_attributes }
        feedback.reload
        expect(response).to redirect_to(feedback_url(feedback))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        feedback = Feedback.create! valid_attributes
        patch feedback_url(feedback), params: { feedback: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested feedback" do
      feedback = Feedback.create! valid_attributes
      expect {
        delete feedback_url(feedback)
      }.to change(Feedback, :count).by(-1)
    end

    it "redirects to the feedbacks list" do
      feedback = Feedback.create! valid_attributes
      delete feedback_url(feedback)
      expect(response).to redirect_to(feedbacks_url)
    end
  end
end
